version: '3'
services:
  mongodb:
    container_name: mongo
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    container_name: node
    build: ./node-backend/
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    container_name: react
    build: ./react-frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - backend
